version: '3.5'

services:
    server:
      image: backend:withoutFrontUrl
      ports:
        - 8000:8000
      environment:
        - REDIS=redis
        - REDIS_PORT=6379
        - DB_HOST=db
        - DB_NAME=tietokanta
        - DB_USERNAME=abdelkarim
        - DB_PASSWORD=example
      depends_on:
        - db

    app:
      image: frontend:withoutApiUrl
      ports:
        - 5000:5000
  
    redis:
      image: redis
      ports:
        - 6379:6379
    db:
      image: postgres
      volumes:
        - ./database/data:/var/lib/postgresql/data/
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=example
        - POSTGRES_USER=abdelkarim
        - POSTGRES_DB=tietokanta
    proxy:
      image: jwilder/nginx-proxy
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - /var/run/docker.sock:/tmp/docker.sock:ro
      ports:
        - 80:80
      restart: always
      depends_on:
        - app
        - server

volumes:
  database:
