version: '3.5'

services:
    redis:
      image: redis
    db:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=example
        - POSTGRES_USER=abdelkarim
        - POSTGRES_DB=tietokanta
    server:
      image: backend
      ports:
        - 8000:8000
      volumes:
        - ./logs.txt:/usr/src/app/logs.txt
      environment:
        - REDIS=redis
        - REDIS_PORT=6379
        - DB_HOST=db
        - DB_NAME=tietokanta
        - DB_USERNAME=abdelkarim
        - DB_PASSWORD=example
      depends_on:
        - db
        - redis
    app:
      image: frontend
    proxy:
      image: jwilder/nginx-proxy
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - /var/run/docker.sock:/tmp/docker.sock:ro
      ports:
        - 80:80
      restart: always
      depends_on:
        - app
        - server
