version: '3.5'

services:
    server:
      image: backend
      ports:
        - 8000:8000
      volumes:
        - ./logs.txt:/usr/src/app/logs.txt
    app:
      image: frontend
      ports:
        - 5000:5000
